-- CRIAR USUARIOS 
CREATE USER joyce WITH PASSWORD 'ecyoj';
CREATE USER felipe WITH PASSWORD 'epilef'; 
CREATE USER rafael WITH PASSWORD 'leafar'; 

-- PERMITIR
GRANT SELECT ON ALL TABLES IN SCHEMA PUBLIC TO joyce;
GRANT INSERT ON ALL TABLES IN SCHEMA PUBLIC TO rafael;
GRANT INSERT ON ALL TABLES IN SCHEMA PUBLIC TO felipe;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA PUBLIC TO rafael;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA PUBLIC TO felipe;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA PUBLIC TO joyce;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA PUBLIC TO joyce;

-- REVOGAR
REVOKE UPDATE ON ALL TABLES IN SCHEMA PUBLIC FROM felipe;
REVOKE UPDATE ON ALL TABLES IN SCHEMA PUBLIC FROM rafael;
REVOKE SELECT ON ALL TABLES IN SCHEMA PUBLIC FROM joyce;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA PUBLIC FROM joyce;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA PUBLIC FROM joyce;
